services:
  wordivore:
    container_name: wordivore
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Manila
    volumes:
      - ./logs:/home/app/logs
    restart: unless-stopped